---
title: "Untitled"
format: html
---


# Set up

```{r}
library(tidyverse)
library(readxl)
library(tidymodels)
library(embed)

olink_data <- read_tsv("../olink_data/phase2_unbridged_data.tsv")
soma_data <- read_tsv("../soma_data/soma_data.tsv")
manifest <- read_excel("../metadata/samples_2025-05-12.xlsx") 
```

# Samples subset

```{r}
soma_id <- 
    soma_data |> 
    filter(!is.na(DAid)) |> 
    distinct(DAid)

meta <- 
    manifest |> 
    filter(DAid %in% soma_id$DAid) |> 
    select(DAid, Cohort, Class, Diagnose, Disease, Age, Sex, BMI) |> 
    mutate(Disease = case_when(Cohort == "BAMS" & Diagnose == "4_random" ~ "Healthy - 4 (BAMSE)",
    Cohort == "BAMS" & Diagnose == "8_random" ~ "Healthy - 8 (BAMSE)",
    Cohort == "BAMS" & Diagnose == "16_random" ~ "Healthy - 16 (BAMSE)",
    Cohort == "BAMS" & Diagnose == "24_random" ~ "Healthy - 24 (BAMSE)",
    Cohort == "PARD" & Diagnose == "PD" ~ "Parkinson's disease",
    Cohort == "PARD" & Diagnose == "Healthy control" ~ "Healthy (PD)",
    Cohort == "PREG" ~ "Pregnancy",
    Cohort == "UCA2" & Diagnose == "OVC" ~ "Ovarian cancer",
    Cohort == "UCA2" & Diagnose == "PRC" ~ "Prostate cancer",
    Cohort == "UCA2" & Diagnose == "CRC" ~ "Colorectal cancer",
    Cohort == "UCA2" & Diagnose == "LUNG" ~ "Lung cancer (UCAN)",
    Cohort == "UCA2" & Diagnose == "BRC" ~ "Breast cancer (UCAN)",
    T ~ Disease),
    Class = case_when(Cohort == "BAMS" ~ "Healthy",
    Cohort == "UCA2" ~ "Cancer",
    Cohort == "PREG" ~ "Pregnancy",
    Cohort == "BAMS" ~ "Childhood development",
    Cohort == "PARD" & Diagnose == "PD" ~ "Neurologic",
    Cohort == "PARD" & Diagnose == "Healthy control" ~ "Healthy",
    T ~ Class))

data_olink <- 
    olink_data |> 
    filter(DAid %in% soma_id$DAid)

data_soma <- 
    soma_data |> 
    mutate(RFU = log2(RFU))
```

## Plot

```{r}
meta |> 
    filter(is.na(Disease)) |> 
    count(Cohort, Diagnose)

disease_n <- 
    meta |> 
    count(Class, Disease) |> 
    mutate(Class = factor(Class)) |> 
    arrange(Class) 

disease_n |> 
    mutate(Disease = factor(Disease, levels = unique(disease_n$Disease))) |> 
    ggplot(aes(Disease, n, fill = Class)) +
    geom_col() +
    geom_text(aes(label = n, color = Class, y = n +10)) +
    coord_flip() +
    scale_color_manual(values = pal_class)+
    scale_fill_manual(values = pal_class) +
    theme_hpa()

ggsave(savepath("disease_n.png"), h = 8, w =7)
```
# UMAP

```{r}
umap_olink <- do_umap(data = data_olink, wide = F)
umap_soma <- do_umap(data = data_soma, wide = F)

umap_combined <- 
    umap_olink |> 
    mutate(Platform = "Olink") |> 
    bind_rows(umap_soma |> 
    mutate(Platform = "Somalogic"))

umap_combined |> 
    left_join(meta, by = "DAid") |> 
    ggplot(aes(UMAP1, UMAP2, color = Disease)) +
    geom_point() +
    facet_wrap(~Platform) +
    theme_hpa()
```


# ANOVA

## Olink

```{r}
data_anova_olink <-
  data_olink |>
  select(DAid, Assay, NPX) %>%
  left_join(meta |>
              select(DAid, Disease, Age, Sex, BMI), by = "DAid") |>
  mutate(BMI = ifelse(BMI == 0, NA, BMI))

#saveRDS(data_anova, savepath_data("ANOVA", "anova_dat.rds"))

# Run ANOVA for all proteins
anova_olink <-
  map_df(unique(data_anova_olink$Assay), function(protein) {
    do_anova(df = data_anova_olink,
             protein = protein)
  })

# Adjust p-values
anova_olink_adj <-
  anova_olink |>
  filter(term != "(Intercept)") |>
  mutate(p.adjusted = p.adjust(p.value, method = "BH")) |>
  relocate(p.adjusted, .after = p.value)

plot_variance(anova_res_adjusted = anova_olink_adj, perc_variation = 45)
```

## Somalogic

```{r}
data_anova_soma<-
  data_soma |>
  select(DAid, Assay, NPX = RFU) %>%
  left_join(meta |>
              select(DAid, Disease, Age, Sex, BMI), by = "DAid") |>
  mutate(BMI = ifelse(BMI == 0, NA, BMI))

#saveRDS(data_anova, savepath_data("ANOVA", "anova_dat.rds"))

# Run ANOVA for all proteins
anova_soma <-
  map_df(unique(data_anova_soma$Assay), function(protein) {
    do_anova(df = data_anova_soma,
             protein = protein)
  })

# Adjust p-values
anova_soma_adj <-
  anova_soma |>
  filter(term != "(Intercept)") |>
  mutate(p.adjusted = p.adjust(p.value, method = "BH")) |>
  relocate(p.adjusted, .after = p.value)

plot_variance(anova_res_adjusted = anova_soma_adj, perc_variation = 45)
```

## Comparison

```{r}
overlapping_proteins <- 
    data_soma |> 
    distinct(EntrezGeneSymbol) |> 
    filter(EntrezGeneSymbol %in% data_olink$Assay) |> 
    pull(EntrezGeneSymbol)

anova_soma_adj
anova_olink_adj
```
### Plot up/down?

### 

# ML (separate)

```{r}

```

# ML (combined)

```{r}

```
# Age prediction Soma/Olink


```{r}
meta_age <- 
    meta |> 
    filter(!is.na(Age)) |> 
    select(DAid, Age)

data_age <- 
    data_olink |> 
    filter(DAid %in% meta_age$DAid) |> 
    select(DAid, Assay, NPX) |> 
    pivot_wider(names_from = Assay, 
    values_from = NPX) |> 
    left_join(meta_age, by = "DAid") 

split_age <- generate_split(data = data_age, variable_stratify = "Age")


age_prediction <- 
    continuous_prediction(split_train = split_age$data_train,
           split_test = split_age$data_test,
           variable_predict = "Age",
           seed = 213) 

```