---
title: "Disease reports"
format: 
  html:
    theme: cosmo       # professional Bootswatch theme
    toc: true          # enable table of contents
    toc-title: "Contents"
    toc-location: left # table of contents in sidebar
    number-sections: true
    code-fold: true    # allow hiding code blocks
params:
  disease: "Lung cancer"
---

```{r}
# Load any required setup
library(tidyverse)
source("initialize.R")
##
# Access the parameter
disease <- params$disease
cat("Running analysis for:", disease, "\n")

all_cancers <- c("Pancreatic cancer", "Ovarian cancer", "Breast cancer", "Lung cancer", "Colorectal cancer", "Prostate cancer")
```

# Data preparation 

```{r}
other_controls_olink <- 
  manifest_olink |> 
  filter(!Disease %in% all_cancers,
  !Disease %in% c("Control", "Healthy", "Healthy control", "No cognitive impairment", "No diagnosis", "healthy"),
!is.na(Disease)) |>
  distinct(DAid)

# Healthy comparison
meta_healthy_olink <- 
  manifest_olink |> 
  filter(Cohort == "SCAP"| Disease == disease) |> 
  select(DAid, Age, Sex, BMI, Disease)
```

# Differential abundance analyses

## Olink 

```{r}
data_healthy_olink <- 
  data_ht_all |> 
  select(-DAid_batch, -Batch) |> 
  filter(DAid %in% meta_healthy_olink$DAid) |> 
  pivot_wider(names_from = Assay, values_from = NPX)

de_healthy_olink <-     
    do_limma_disease(data_wide = data_healthy_olink,
                     metadata = meta_healthy_olink,
                     disease = disease,
                     controls = "Healthy",
                     correct = F,
                     cutoff = 0) 


meta_cancer_olink <- 
  manifest_olink |> 
  filter(Disease %in% all_cancers) |> 
  select(DAid, Age, Sex, BMI, Disease)

data_cancer_olink <- 
  data_ht_all |> 
  select(-DAid_batch, -Batch) |> 
  filter(DAid %in% meta_cancer_olink$DAid) |> 
  pivot_wider(names_from = Assay, values_from = NPX)

de_cancer_olink <-     
    do_limma_disease(data_wide = data_cancer_olink,
                     metadata = meta_cancer_olink,
                     disease = disease,
                     controls = "Cancer",
                     correct = F,
                     cutoff = 0) 


# Pan-disease comparison
meta_disease_olink <- 
  manifest_olink |> 
  filter(DAid %in% unique(other_controls_olink$DAid) | Disease == disease) |> 
  select(DAid, Age, Sex, BMI, Disease)

data_disease_olink <- 
  data_ht_all |> 
  select(-DAid_batch, -Batch) |> 
  filter(DAid %in% meta_disease_olink$DAid) |> 
  pivot_wider(names_from = Assay, values_from = NPX)

de_disease_olink <-     
    do_limma_disease(data_wide = data_disease_olink,
                     metadata = meta_disease_olink,
                     disease = disease,
                     controls = "Disease",
                     correct = F,
                     cutoff = 0) 


```

### Volcano plots

```{r}
volcano_healthy_olink <- plot_volcano(de_healthy_olink, multiple = T, nrow = 2, cutoff = 0) + ggtitle("Healthy")
volcano_cancer_olink <- plot_volcano(de_cancer_olink, multiple = T, nrow = 2, cutoff = 0) + ggtitle("Pan-cancer")
volcano_disease_olink <- plot_volcano(de_disease_olink, multiple = T, nrow = 2, cutoff = 0) + ggtitle("Pan-disease")

volcano_healthy_olink + volcano_cancer_olink + volcano_disease_olink
ggsave(paste0("results/de_", disease, "_Olink.png"), h = 5, w = 12)
```
### Examples

```{r}
de_combined_olink <- 
  de_healthy_olink |> 
  bind_rows(de_cancer_olink) |> 
  bind_rows(de_disease_olink)

top_assays <- 
  de_combined_olink |> 
  group_by(Control) |> 
  top_n(20, abs(logFC)) |> 
  ungroup() |> 
  distinct(Assay)

my_palette <- colorRampPalette(c("white", "#DDC49C", "red"))(100)

de_combined_olink |>
  filter(Assay %in% top_assays$Assay) |> 
  select(Assay, logFC, Control) |> 
  pivot_wider(names_from = Control, values_from = logFC) |> 
  column_to_rownames("Assay") |> 
  pheatmap(color = my_palette) |> 
  as.ggplot()

ggsave(paste0("results/de_pheatmap_", disease, "_Olink.png"), h = 8, w = 5)


top_5 <- 
  de_combined_olink |>
  filter(Assay %in% top_assays$Assay) |> 
  select(Assay, logFC, Control) |> 
  pivot_wider(names_from = Control, values_from = logFC) |> 
  mutate(rank_healthy = rank(-Healthy),
rank_disease = rank(-Disease),
rank_cancer = rank(-Cancer)) |> 
  group_by_all() |> 
mutate(sum_rank = sum(rank_healthy, rank_cancer, rank_disease)) |> 
  arrange(sum_rank) |> 
  head(5)


cancer_controls <- 
  manifest_olink |> 
  filter(Disease %in% all_cancers,
  Disease != disease) |> 
  distinct(Disease) |> 
  pull()

disease_controls <- 
  manifest_olink |> 
  filter(DAid %in% other_controls_olink$DAid) |> 
  distinct(Disease) |> 
  pull()


levels <- c(disease, "Healthy", cancer_controls, disease_controls)
pal_controls <- c(disease = "darkred", "Healthy" = "grey", "Pan-cancer controls" = "#DDC49C", "Pan-disease controls" = "#99B2A6")

manifest_olink_controls <- 
  manifest_olink |> 
  mutate(Type = case_when(Disease == disease ~ Disease,
  Disease == "Healthy" ~ Disease,
Disease %in% cancer_controls ~ "Pan-cancer controls",
Disease %in% disease_controls ~ "Pan-disease controls")) |> 
  mutate(Disease = factor(Disease, levels = c(disease, "Healthy", cancer_controls, disease_controls)))

data_ht_all |>
      filter(Assay %in% top_5$Assay,
      DAid %in% manifest_olink$DAid) |>
      select(DAid, Assay, NPX) |>
      left_join(manifest_olink_controls |>
                  select(DAid, Disease, Type),
                by = "DAid") |>
    mutate(Disease = factor(Disease, levels = c(disease, "Healthy", cancer_controls, disease_controls))) |> 
filter(!is.na(Disease)) |> 
        ggplot(aes(Disease,
                   NPX,
                   fill = Type,
                   color = Type)) +
        geom_quasirandom(alpha = 0.7
) +
        geom_boxplot(
          alpha = 0.3,
          outlier.color = NA,
          color = "grey20",
          show.legend = F
        ) +
 scale_color_manual(
    values = pal_controls,
    na.value = "darkred")  +
 scale_fill_manual(
    values = pal_controls,
    na.value = "darkred") +  
  facet_wrap( ~ Assay, scales = "free_y", ncol = 1) +
        theme_hpa(angled = T) +
        xlab("") 

ggsave(paste0("results/de_examples_", disease, "_Olink.png"), h = 10, w = 10)

```

## Somalogic

# Overlap

# Comparison